apiVersion: apps/v1
kind: Deployment
metadata:
  name: zbook-redis
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: zbook-redis
  template:
    metadata:
      labels:
        app: zbook-redis
    spec:
      containers:
        - name: zbook-redis
          image: {{ .Values.redis.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: zbook-redis-pv-claim