apiVersion: v1
kind: PersistentVolume
metadata:
  name: zbook-redis-pv-volume
  labels:
    type: local
    app: zbook-redis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.redis.resources.requests.storage }}
  hostPath:
    path: {{ .Values.redis.hostPath | quote }}