apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zbook-database-pv-claim
  labels:
    app: zbook-database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.database.resources.requests.storage }}