apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zbook-redis-pv-claim
  labels:
    app: zbook-redis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.redis.resources.requests.storage }}