apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zbook-minio-pv-claim
  labels:
    app: zbook-minio
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.minio.resources.requests.storage }}