apiVersion: v1
kind: Service
metadata:
  name: zbook-redis-service
  labels:
    app: zbook-redis
spec:
  selector:
    app: zbook-redis
  type: ClusterIP
  ports:
    - name: tcp-redis
      port: 6379