apiVersion: v1
kind: Service
metadata:
  name: zbook-frontend-service
  labels:
    app: zbook-frontend
spec:
  selector:
    app: zbook-frontend
  type: ClusterIP
  ports:
    - name: tcp-frontend
      port: 3000
