apiVersion: v1
kind: Service
metadata:
  name: zbook-backend-api-service
  labels:
    app: zbook-backend
spec:
  selector:
    app: zbook-backend
  type: ClusterIP
  ports:
    - name: tcp-backend-api
      port: 8080
---   
apiVersion: v1
kind: Service
metadata:
  name: zbook-backend-grpc-service
  labels:
    app: zbook-backend
spec:
  selector:
    app: zbook-backend
  type: ClusterIP
  ports:
    - name: grpc-backend-grpc
      port: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: zbook-backend-websocket-service
  labels:
    app: zbook-backend
spec:
  selector:
    app: zbook-backend
  type: ClusterIP
  ports:
    - name: tcp-backend-websocket
      port: 9099