apiVersion: v1
kind: Service
metadata:
  name: zbook-minio-webui-service
  labels:
    app: zbook-minio
spec:
  selector:
    app: zbook-minio
  type: ClusterIP
  ports:
    - name: tcp-minio-webui
      port: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: zbook-minio-api-service
  labels:
    app: zbook-minio
spec:
  selector:
    app: zbook-minio
  type: ClusterIP
  ports:
    - name: tcp-minio-api
      port: 9000
