apiVersion: v1
kind: Service
metadata:
  name: zbook-database-service
  labels:
    app: zbook-database
spec:
  selector:
    app: zbook-database
  type: ClusterIP
  ports:
    - name: tcp-database
      port: 5432